# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui03.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gui03(object):
    def setupUi(self, Gui03):
        Gui03.setObjectName("Gui03")
        Gui03.resize(1500, 1000)
        Gui03.setMouseTracking(False)
        Gui03.setStyleSheet("color: rgb(139, 0, 0);")
        self.title = QtWidgets.QLabel(Gui03)
        self.title.setGeometry(QtCore.QRect(500, 10, 651, 161))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(255, 255, 255);")
        self.title.setObjectName("title")
        self.title_2 = QtWidgets.QLabel(Gui03)
        self.title_2.setGeometry(QtCore.QRect(530, 90, 571, 161))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.title_2.setFont(font)
        self.title_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.title_2.setObjectName("title_2")
        self.Alice = QtWidgets.QPushButton(Gui03)
        self.Alice.setGeometry(QtCore.QRect(90, 300, 391, 521))
        self.Alice.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Alice.setStyleSheet("background-image: url(:/AliceCV.jpg);")
        self.Alice.setText("")
        self.Alice.setObjectName("Alice")
        self.developer = QtWidgets.QPushButton(Gui03)
        self.developer.setGeometry(QtCore.QRect(550, 300, 391, 521))
        self.developer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.developer.setStyleSheet("background-image: url(:/DeveloperCV.jpg);")
        self.developer.setText("")
        self.developer.setObjectName("developer")
        self.modern = QtWidgets.QPushButton(Gui03)
        self.modern.setGeometry(QtCore.QRect(1010, 300, 391, 521))
        self.modern.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.modern.setStyleSheet("\n"
"background-image: url(:/ModernCV.png);")
        self.modern.setText("")
        self.modern.setObjectName("modern")
        self.title_3 = QtWidgets.QLabel(Gui03)
        self.title_3.setGeometry(QtCore.QRect(580, 820, 431, 161))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.title_3.setFont(font)
        self.title_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.title_3.setObjectName("title_3")
        self.graphicsView = QtWidgets.QGraphicsView(Gui03)
        self.graphicsView.setGeometry(QtCore.QRect(0, -320, 1511, 1641))
        self.graphicsView.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.title.raise_()
        self.title_2.raise_()
        self.Alice.raise_()
        self.developer.raise_()
        self.modern.raise_()
        self.title_3.raise_()

        self.retranslateUi(Gui03)
        QtCore.QMetaObject.connectSlotsByName(Gui03)

    def retranslateUi(self, Gui03):
        _translate = QtCore.QCoreApplication.translate
        Gui03.setWindowTitle(_translate("Gui03", "gui"))
        self.title.setText(_translate("Gui03", "Resume Creator"))
        self.title_2.setText(_translate("Gui03", "Design & Create by Ali Safarpour & Ali Gholamian"))
        self.title_3.setText(_translate("Gui03", "Chosse Your Template"))
import mainresource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gui03 = QtWidgets.QWidget()
    ui = Ui_Gui03()
    ui.setupUi(Gui03)
    Gui03.show()
    sys.exit(app.exec_())
